# Generated by Django 3.2 on 2021-04-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('website', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('freelancer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('nilai', models.IntegerField()),
            ],
        ),
    ]
