# Generated by Django 3.2 on 2021-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_portfolio_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('deskripsi', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('pengirim', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='mail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='about',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
