# Generated by Django 3.2 on 2021-05-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_skill_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='gambar',
            new_name='gambar1',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='deskripsi',
            new_name='deskripsi1',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='gambar',
            new_name='gambar1',
        ),
        migrations.AddField(
            model_name='blog',
            name='deskripsi2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='gambar2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='deskripsi2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='gambar2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
