# Generated by Django 3.2 on 2021-05-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210507_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='kategori',
            new_name='judul',
        ),
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
