# Generated by Django 3.2 on 2021-05-10 07:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210508_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='deskripsi2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
