# Generated by Django 3.2 on 2021-05-10 08:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_portfolio_deskripsi2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='deskripsi',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='deskripsi2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='deskripsi1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
