# Generated by Django 3.2 on 2021-04-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='nilai',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
