# Generated by Django 3.2 on 2021-05-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210424_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
