# Generated by Django 3.2 on 2021-05-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210505_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.kategori'),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
